// Generated by CoffeeScript 1.3.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.app = (_ref = window.app) != null ? _ref : {};

  jQuery(function() {
    var ListView, Question, Questions;
    Question = (function(_super) {

      __extends(Question, _super);

      function Question() {
        return Question.__super__.constructor.apply(this, arguments);
      }

      Question.prototype.defaults = {
        question: 'Question',
        answer: 'Answer'
      };

      return Question;

    })(Backbone.Model);
    Questions = (function(_super) {

      __extends(Questions, _super);

      function Questions() {
        return Questions.__super__.constructor.apply(this, arguments);
      }

      Questions.prototype.model = Question;

      Questions.prototype.url = 'questions';

      Questions.prototype.initialize = function() {
        return this.bind('all', function(eventType) {
          console.log("" + eventType + " event occurred! The collection is now:");
          return console.log(this);
        });
      };

      return Questions;

    })(Backbone.Collection);
    ListView = (function(_super) {

      __extends(ListView, _super);

      function ListView() {
        return ListView.__super__.constructor.apply(this, arguments);
      }

      ListView.prototype.el = $('body');

      ListView.prototype.initialize = function() {
        _.bindAll(this);
        app.questions.bind('add', this.appendQuestion);
        app.questions.bind('reset', this.resetQuestions);
        return this.render();
      };

      ListView.prototype.render = function() {
        $(this.el).append('<input type="text" id="question"></input><input type="text" id="answer"></input>');
        $(this.el).append('<button>Add question</button>');
        return $(this.el).append('<ul></ul>');
      };

      ListView.prototype.addQuestion = function() {
        return app.questions.create({
          question: $('#question').val(),
          answer: $('#answer').val()
        });
      };

      ListView.prototype.appendQuestion = function(question) {
        return $('ul').append("<li>" + (question.get('question')) + "? " + (question.get('answer')));
      };

      ListView.prototype.resetQuestions = function() {
        var question, _i, _len, _ref1, _results;
        $('ul').innerHTML = "";
        _ref1 = app.questions.models;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          question = _ref1[_i];
          _results.push(this.appendQuestion(question));
        }
        return _results;
      };

      ListView.prototype.events = {
        'click button': 'addQuestion'
      };

      return ListView;

    })(Backbone.View);
    app.questions = new Questions;
    app.questions.fetch();
    return app.list_view = new ListView;
  });

}).call(this);
